### ISSUE TITLE
Script panic

### ISSUE THREAD

**Issue by presidenten** [RCdiy/OpenTxLua#6]
When I assign the script to display and try to start it, I get "script panic - not enough memory".
I dont have any other custom lua scripts installed, only 6 models added, and 1 gv variable is assigned. 

Whats going on? How can I make it run?

Running Opentx 2.2.1

**Comment by presidenten** [comment]
I removed everything I didnt need, like pilotgps and stuff like that, and now it works. 
So never mind :-)

**Comment by RCdiy** [comment]
Glad. 
Apologies for not responding. 
Not well. 

Rav

RCdiy
Stay Safe & Have Fun
http://RCdiy.ca

**Comment by presidenten** [comment]
No worries!
I tried it out yesterday and it works great!

Also found a video by JB on how to enable luac to avoid memory issues.
Linking here for future references:
https://youtu.be/1Ccz5gxAX2M
